name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.SSH_HOST }}
          if_key_exists: replace

      - name: Deploy to Live Server and install
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no vulps@161.97.68.166 \
            'cd /var/www/html/ajmcallister && git remote -v && git pull
